version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
